### ISSUE TITLE
Detection of dead ends

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/sport-activities-features#18]
We should provide a support for discovery of dead ends, e. g. https://en.wikipedia.org/wiki/Dead_end_(street)

It would be nice to return the information, whether the cyclist encountered a dead end (or more than one) during the workout.

@luckyLukac - can we assign it to you?

**Comment by luckyLukac** [comment]
Sure :)

**Comment by firefly-cpp** [comment]
Thanks @luckyLukac!

**Comment by firefly-cpp** [comment]
Hi @luckyLukac!

How is the project coming along?

**Comment by luckyLukac** [comment]
Hi,

unfortunately I have been quite busy with all kinds of stuff in the recent times, thus there was no progress made regarding the project. Since I will have more spare time in the upcoming weeks, I will start the work on the detection of dead ends soon.

Thanks @firefly-cpp for the kind reminder. 😀

**Comment by firefly-cpp** [comment]
Proposed in #37. Thanks @luckyLukac!
